name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install `cargo deny`
      run: cargo install cargo-deny
    - name: Check Licenses
      run: cargo deny check
    - name: Format code
      run: cargo fmt --all
    - name: Clippy lints
      run: cargo clippy --features full
    - name: Build
      run: cargo build --verbose --features full
    - name: Run tests
      run: cargo test --verbose --features full
